version: '3.7'

networks:
  intranet:
    driver: bridge

services:

  oathkeeper:
    image: oryd/oathkeeper:v0.40
    ports:
      - 4455:4455
      - 4456:4456
    command: serve -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - intranet
    volumes:
      - ./oathkeeper/config:/etc/config/oathkeeper
  
  aad-authservice:
    image: pcibraro/aad-authservice:latest
    #ports:
    #  - 9005:9005
    environment:
      - SERVER_PORT=${SERVER_PORT:-9005}
      - AAD_TENANT=${ADD_TENANT}
      - AAD_CLIENT_ID=${AAD_CLIENT}
      - AAD_CLIENT_SECRET=${AAD_CLIENT_SECRET}
      - REQUIRE_SECURE_COOKIE=${REQUIRE_SECURE_COOKIE:-false}
      - OATHKEEPER_URL=${OATHKEEPER_URL}
    restart: on-failure
    networks:
      - intranet

  sample-api:
    image: pcibraro/protected-sample-service:latest
    ports:
      - 9006:9006
    environment:
      - SERVER_PORT=9006
    restart: on-failure
    networks:
      - intranet
    

  